### ISSUE TITLE
Frequent segmentation faults in Create app

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#10]
Segmentation faults happen semi-randomly in Create app, especially when manipulating objects.

**Comment by ksuprynowicz** [comment]
When Overte is built with no optimization, create app crashes are rarer, but they still happen.
The error message is:
`malloc_consolidate(): unaligned fastbin chunk detected`
Here's the call stack:
![image](https://user-images.githubusercontent.com/11568651/152680192-31344750-08c1-4ce7-82fc-8708dfeb4f24.png)

**Comment by JulianGro** [comment]
I think these crashes might only happen on Linux.
I have always had frequent crashes on Linux using the Create app. As far as I know, others on Windows have not had issues like this.

**Comment by HifiExperiments** [comment]
I’ve tried and failed to fix this in the past.  I think it’s a script threading issue, but it might be a deeper Qt memory problem.  maybe the script engine changes will help

**Comment by ksuprynowicz** [comment]
Finally fixed :)
