### ISSUE TITLE
Increase default FOV

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#1059]
The default FOV is way too narrow. Would it be ok to increase default value to about 60?
I play with FOV set to about 66 typically and default value is 45.

**Comment by JulianGro** [comment]
I would suggest either 50° or 55°.
It's hard to tell, but for me, it feels like objects are too far away if I am on 60°. For sitting in a large group of people, I see how a higher FOV is helpful, but it does take away from 1 on 1 intimacy and object interaction. The default 45° seem like the most realistic to me in terms of distance, but I would also prefer something a little higher, like 50° or 55°.
VRChat's default vertical FOV is 60°, so I would propose the value closer to that, which is 55°.

**Comment by ksuprynowicz** [comment]
55° sounds very good to me as the default value.

**Comment by Meister1593** [comment]
I personally use 90-100 degree and 70 is even default on something like Minecraft
I think 60 should be reasonable for most people

**Comment by JulianGro** [comment]
I wonder if we should have different FOV for first person and third person.
Because, looking at it now, 45° looks like the sweet spot to me if you are in third person mode.
