### ISSUE TITLE
Wayland Qt platform plugin missing from AppImage

### ISSUE THREAD

**Issue by galister** [overte-org/overte#1074]
```
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, webgl, xcb.
```

And so the only way to run Interface is by forcing it though XWayland with `QT_QPA_PLATFORM=xcb`.

**Comment by JulianGro** [comment]
This should throw a warning and be handled automatically: https://github.com/overte-org/overte-builder/blob/master/templates/Overte/AppRun

**Comment by JulianGro** [comment]
@galister could you try https://data.moto9000.moe/Overte-2024.07.1-rc2-debug-x86_64_no_Wayland_generic.AppImage to see if that disables the plugin properly when missing?
