### ISSUE TITLE
Use a different hue of blue for links in armorchat

### ISSUE THREAD

**Issue by AnotherFoxGuy** [overte-org/overte#1082]
The current one is really difficult to read sometimes

https://webaim.org/resources/contrastchecker/?fcolor=1005FB&bcolor=262626
https://webaim.org/resources/contrastchecker/?fcolor=1005FB&bcolor=1A1A1A

**Comment by AnotherFoxGuy** [comment]
Example:
![interface_2024-07-13_21-23-03](https://github.com/user-attachments/assets/26838f61-317e-4c25-ad45-05f6fb9bc9ed)
![interface_2024-07-13_21-23-13](https://github.com/user-attachments/assets/dbc5cadc-6064-4dc9-aa1c-8075faa785f7)

**Comment by ksuprynowicz** [comment]
#B3AFFD works really well IMO and passes all tests.

**Comment by Armored-Dragon** [comment]
![Screenshot_20240713_144159](https://github.com/user-attachments/assets/dfa0aaca-545c-40a2-83c3-37e108fb39dd) 
This was before the fix.
