### ISSUE TITLE
Incorrect labels in Overte installer components on Windows

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#109]
![e4857937df8814189b2c65f1b38c02a6](https://user-images.githubusercontent.com/11568651/175834600-0b8156bc-4904-4d9c-a41c-a23d47f37c95.png)

**Comment by daleglass** [comment]
hmm, is this still a thing? I can't find those strings in the repo

**Comment by ksuprynowicz** [comment]
I think it still happens. I will check as soon as the zlib PR builds.

**Comment by daleglass** [comment]
Seems correct:

https://i.imgur.com/anzbOEY.png

**Comment by daleglass** [comment]
![anzbOEY](https://user-images.githubusercontent.com/51060919/179366602-519d74b4-7af6-40cf-b484-c712f823018c.png)

**Comment by daleglass** [comment]
Confirmed at the dev meeting, everything seems to be in order
