### ISSUE TITLE
Create App: “permission to view URL” empties fields

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte#1130]
When selecting a field in Create app, which doesn't allow you to view the URL, it will empty the field when selected.
![Bildschirmfoto vom 2024-09-06 22-45-31](https://github.com/user-attachments/assets/ea5de79d-478a-4aa6-be33-36273b431c58)

**Comment by AleziaKurdis** [comment]
Not a fun one to fix.

**Comment by HifiExperiments** [comment]
I don't think it's that complicated...maybe just disallow completely clearing the value if you don't have url permission, that way you can still change it, just not clear it.

**Comment by Armored-Dragon** [comment]
> I don't think it's that complicated...maybe just disallow completely clearing the value if you don't have url permission, that way you can still change it, just not clear it.

I tried. It blew up.

**Comment by JulianGro** [comment]
Maybe we should partially disable this feature for now, by tying it to the create permissions?

**Comment by HifiExperiments** [comment]
I think that will be messier to be honest.  I talked with @Armored-Dragon and I will give fixing it a shot next week
