### ISSUE TITLE
[ ArmoredChat.js ] Text can not append to previous messages

### ISSUE THREAD

**Issue by Armored-Dragon** [overte-org/overte#1142]
In the chat application text is supposed to append to previous messages under specific circumstances. This currently does not function. This results in each message being rendered as individual messages.

**Comment by daleglass** [comment]
What are those circumstances?

**Comment by Armored-Dragon** [comment]
> What are those circumstances?

https://github.com/overte-org/overte/blob/808135b6c4a63c12f8dd35fc8aa9741a69ad3263/scripts/communityScripts/armored-chat/armored_chat.qml#L494

When a message is going to be rendered, it will check if the new message is from the same author as the previously rendered image, and that less than a minute passed since the last message.

**Comment by Armored-Dragon** [comment]
This was fixed in https://github.com/overte-org/overte/pull/1210
