### ISSUE TITLE
Switch away from Vircadia CDN

### ISSUE THREAD

**Issue by daleglass** [overte-org/overte#116]
There's a bunch of URLs like https://cdn-1.vircadia.com/us-e-1/Bazaar/Avatars/Mike/img/icon.png all over the code.

Since Vircadia doesn't like us, we should switch to an alternative.

**Comment by SilverfishVR** [comment]
don't forget: https://cdn-1.vircadia.com/eu-c-1/vircadia-public/sounds/Collisions-otherorganic/Body_Hits_Impact.wav in the avatar menu

**Comment by JulianGro** [comment]
Is that a joke? I mean it is a collision sound and I have never heard a collision in this.
