### ISSUE TITLE
Text entities: Cyrillic characters are no longer displayed

### ISSUE THREAD

**Issue by Morgenstern29** [overte-org/overte#1169]
Cyrillic characters are no longer displayed in the Text entities. Interface and server version 2024.07.1. Font: Roboto.
![Screenshot_1](https://github.com/user-attachments/assets/fd9f42ad-567f-4e66-9812-863e53534be6)

**Comment by HifiExperiments** [comment]
huh!  did this work before?

I don’t know why the old Roboto font would have included these glyphs…if anyone could find a version of Roboto that did include them, I could update the new font file

**Comment by JulianGro** [comment]
I just checked, and Cyrillic characters did actually work.

The normal Roboto font also includes them: https://fonts.google.com/specimen/Roboto/glyphs?query=Roboto

**Comment by AleziaKurdis** [comment]
in the font yes, but on the text entity, i don't think it was. At least before the recent changes.
It never supported accents too.

**Comment by HifiExperiments** [comment]
hm...maybe because I didn't do `-allglyphs` when generating the fonts?

**Comment by HifiExperiments** [comment]
ah yep I see what happened, I will fix it!

**Comment by Morgenstern29** [comment]
> huh!  did this work before?
> 
> I don’t know why the old Roboto font would have included these glyphs…if anyone could find a version of Roboto that did include them, I could update the new font file

Yes, it worked before. So I noticed this bug: all texts consisting of Cyrillic letters were broken. So I tried to fix it but to no avail...
