### ISSUE TITLE
Severe framerate drop/stutter when someone joins or leaves world

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#1180]
Stutter happens when avatar appears or disappears, it can last up to several seconds, and drops the framerate to about 1 fps apparently.
The easiest way to test this is starting two clients and enabling shield on one of them.
Then while moving towards or away from the avatar with shield enabled, severe stutter will happen as avatar disappears and appears.

**Comment by ksuprynowicz** [comment]
The stutter is more severe in VR.
Thanks to Hannu for noticing this one!

**Comment by HifiExperiments** [comment]
so I tried bisecting this a little and I *think* I found:

bad:
```
commit c73566d7f21a30a41a14c84a5c56c84014be55da (HEAD)
Merge: 78bc24cb222 446207a4b43
Author: ksuprynowicz <ksuprynowicz@post.pl>
Date:   Sat Jan 13 11:18:00 2024 +0100

    Merge pull request #721 from HifiExperiments/mirror

    Mirrors + Portals
```

good:
```
commit 78bc24cb222bb832e4bd5a8dea87979d5d7f27cc (HEAD)
Merge: 39df2c975d7 d4112f455b9
Author: ksuprynowicz <ksuprynowicz@post.pl>
Date:   Fri Nov 24 23:24:37 2023 +0100

    Merge pull request #724 from HifiExperiments/luci

    Fix luci
```

so presumably this is due to the mirror PR, which is surprising, since there's not really anything specific to avatars in there.  it's possible this is more related to the fade effect, which I also didn't really touch.  I will keep investigating

**Comment by HifiExperiments** [comment]
it happens in both deferred and forward rendering, so it's not related to the fade effect (which is off in forward mode).  the problem goes away if I comment out this line:
```
            task.addJob<RenderMirrorTask>("RenderMirrorTask" + std::to_string(i) + "Depth" + std::to_string(depth), mirrorInputs, i, cullFunctor, depth);
```
but weirdly, I only have to comment it out in one path.  e.g. if I comment it out in the forward path, I can leave it in the deferred path, and everything works fine (except obviously mirrors don't appear in forward rendering).  but RenderMirrorTask early exits immediately when there are no mirrors (via `renderContext->taskFlow.abortTask();` in SetupMirrorTask), so it's essentially a no-op!

the only thing I can think is that we're hitting some memory limit by having such a large Job tree, which is then put over the top when an avatar loads in?  I guess I will try making some more parts of the Jobs static so they aren't repeatedly created
