### ISSUE TITLE
Tablet text entry doesn't work anymore

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#1184]
It seems that tablet text entry got broken somehow, both in VR and desktop.

**Comment by ksuprynowicz** [comment]
It might be related to this:
https://github.com/overte-org/overte/pull/1046

**Comment by ksuprynowicz** [comment]
It works in 2024.10.1-rc1, so it broke somewhere between then and now.

**Comment by ksuprynowicz** [comment]
@HifiExperiments I might need help with this
I finished bisecting, the commit that tablet input breaks on is this one:
```
ff50d6c2cc35de3543328d605fae0c443fd02c99 is the first bad commit
    automated entity property serialization
```
It's very unexpected that it's related to input at all.

**Comment by HifiExperiments** [comment]
hmmmm the only thing I can think of is maybe something changed with respect to "inputMode", which is a property that web entities have.

**Comment by HifiExperiments** [comment]
oh I see what happened

**Comment by ksuprynowicz** [comment]
I dumped tablet properties, but they look reasonable:
[tabletProperties.json](https://github.com/user-attachments/files/17512081/tabletProperties.json)

**Comment by ksuprynowicz** [comment]
> oh I see what happened

What happened?
