### ISSUE TITLE
(Feature request) Add a way to assign keys to controls

### ISSUE THREAD

**Issue by hardBSDk** [overte-org/overte#1198]

**Comment by Armored-Dragon** [comment]
This has been a longstanding issue for a while. There have been attempts in the past to bring this functionality into this software but they never got completed.
See: https://github.com/overte-org/overte/milestone/4
I will likely be implementing this (or try to at least) with the UUI update https://github.com/orgs/overte-org/projects/8
Closing as (technically) a duplicate of https://github.com/overte-org/overte/issues/110
