### ISSUE TITLE
Lots of assignment clients are being launched, leading the server running out of memory

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#12]
During the domain server operation lots (300 or more) of assignment clients (300 or more) are being launched sometimes, even though only 6 are visible from domain server UI. Restarting assignment client service fixes this for some time.

![image](https://user-images.githubusercontent.com/11568651/152675558-b714e86b-31a4-43fa-b04f-e608ec1d400f.png)

**Comment by daleglass** [comment]
This needs more info: is it only a particular kind of assignment client that gets launched?

Also journald logs could be useful here

**Comment by JulianGro** [comment]
Does this still happen? I have never seen this before or heard of it outside this issue.

**Comment by JulianGro** [comment]
Let's close this and just reopen it if someone runs into the issue again.
