### ISSUE TITLE
Windows Client installer - remote deployment options?

### ISSUE THREAD

**Issue by SteveD-UoC** [overte-org/overte#1225]
Does the Windows Client installer have options which allow it to be deployed remotely?

Options normally are silent/headless installs without the requirement for user interaction.

**Comment by daleglass** [comment]
We're using NSIS for the installer. It's a pretty common one with available documentation.

The docs say that /S performs a silent install, is that suitable for your usage?

**Comment by SteveD-UoC** [comment]
Very possibly, I'll check and reopen if needed.

Thanks.
