### ISSUE TITLE
VIRCADIA_OPTIMIZE cannot be disabled

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte#127]
Setting `VIRCADIA_OPTIMIZE=false` doesn't disable VIRCADIA_OPTIMIZE. I thought this worked at some point.

**Comment by ksuprynowicz** [comment]
I noticed this too in new versions. Adding -DVIRCADIA_OPTIMIZE=0 to cmake still disables it for me though.

**Comment by JulianGro** [comment]
We should fix this in CMake. That should be very easy.
