### ISSUE TITLE
MyAvatar.getDomainMaxScale() and MyAvatar.getDomainMinScale() appear to be returning half of the correct value

### ISSUE THREAD

**Issue by Armored-Dragon** [overte-org/overte#1285]
I ran the commands `MyAvatar.getDomainMaxScale()` and `MyAvatar.getDomainMinScale()` in the Overte Hub using the scripting console, and the values returned were roughly half of the correct value set in the server settings.

I'm not sure if this is a bug as in [the docs](https://apidocs.overte.org/MyAvatar.html#.getDomainMaxScale) it says it can change based on the avatar, and it does, but it does not seem to ever return the expected value.

**Comment by JulianGro** [comment]
It works fine on my end. My domain has a maximum limit of 5,2 meters. If I run `MyAvatar.getHeight()` I get 1.1664968729019165. If I run `MyAvatar.getDomainMaxScale()` I get 4.457791328430176.

5,2 divided by 1,17 is ~4.45

This is in anime-avatars.
The minimum scale also seems to work.

**Comment by Armored-Dragon** [comment]
Ah I may have a misunderstanding on how the avatar scale works. 
So on the server side you set a maximum height in a physical measurement from the foot to the head. So avatars will never be above 5 meters (as an example), and the maximum scalier value is calculated based on your avatars initial height. This would result in a value from `MyAvatar.getDomainMaxScale()` multiplied by your avatar initial height (`MyAvatar.getHeight()`) would result in the correct maximum height allowed by the server in units/meters?

**Comment by JulianGro** [comment]
Seems right.
I am not sure if the height is actually from foot to head, or if it is just the total height (if for example long bunny ears count towards the height).

**Comment by Armored-Dragon** [comment]
Thank you for the clarification!
