### ISSUE TITLE
Snapshot: ability to chose between jpeg and png

### ISSUE THREAD

**Issue by AleziaKurdis** [overte-org/overte#132]
Recently the snap app has been changed to generate png instead of jpeg.
I'm taking a lot of screenshot and jpeg was fine most of the time. 
Since it is now png, this take 8 to 12 time the space on my disk for images that have the quarter of the resolution.

It would be interesting to have a setting to specify the file format of the snapshot. 
it would be also interesting to have a setting to specify the size of the capture (something like: full, 1/4, 1/8)
Sometime it would be cool to be able to be able to have png at full scale to have the best quality.
Sometime to have jpeg to keep this light.
Also if we plan to bring back any snapshot sharing, it might be better to be able to use a lighter format like jpeg

**Comment by daleglass** [comment]
Sounds overall like a good idea, yes, just got to think a bit about API modifications.

I suggest that we add these two functions:

```
getSnapshotFormats(); // Returns an array of supported formats: ["png", "jpg", "webp"]
getAnimatedSnapshotFormats(); // Returns an array of supported formats: ["gif", "webm"]
```

You should be able to already change the format of the screenshots in the UI by just choosing a file extension for the filename, eg, in https://apidocs.overte.org/Window.html#.takeSnapshot

I think we should also add a quality setting, and a format for the video, because I'm working on video encoding.

**Comment by daleglass** [comment]
Okay, so we have:

```
takeSecondaryCamera360Snapshot( cameraPosition, cubemapOutputFormat(opt), notify(opt), filename(opt) )
takeSecondaryCameraSnapshot( notify(opt), filename(opt) )
takeSnapshot( notify(opt), includeAnimated(opt), aspectRatio(opt), filename(opt) )
```

I propose:

```
takeSecondaryCamera360Snapshot( cameraPosition, cubemapOutputFormat(opt), notify(opt), filename(opt), quality(opt) )
takeSecondaryCameraSnapshot( notify(opt), filename(opt), quality(opt) )
takeSnapshot( notify(opt), includeAnimated(opt), aspectRatio(opt), filename(opt), quality(opt), animatedFilename(opt), animatedQuality(opt) )
```

In the last case, it's a bit redundant with the `includeAnimated` parameter, but I want to preserve compatibility.

* The format is indicated by the file extension, and if not set, defaults to whatever the system wants.
* The quality is 0 to 100, and internally is scaled to whatever values the codec uses.

**Comment by ksuprynowicz** [comment]
https://github.com/overte-org/overte/pull/134 solves this. I didn't add quality yet, because it wasn't in original code either, but it can be added in later PR.
