### ISSUE TITLE
FPS seems locked to 60fps

### ISSUE THREAD

**Issue by IF-Adin** [overte-org/overte#15]
My monitor runs at 120hz, so it definitively could run at a higher framerate.

OS: KDE neon User - 5.24 x86_64
Kernel: 5.13.0-28-generic

AMD GPU (6900xt) running on Mesa 21.0.3

**Comment by IF-Adin** [comment]
![Screenshot_20220209_075045](https://user-images.githubusercontent.com/11959695/153137360-453f0542-29cd-4697-a0c3-4d6c7b680523.png)
![Screenshot_20220209_074957](https://user-images.githubusercontent.com/11959695/153137363-1453d03c-f9c5-4086-9e4e-b57b5a551357.png)
![Screenshot_20220209_074121](https://user-images.githubusercontent.com/11959695/153137365-3a4b7066-da9f-4548-a521-8fb48a56ff78.png)

**Comment by IF-Adin** [comment]
Seems @daleglass was working on this. Are you still planning to completely rewrite the settings?

**Comment by Armored-Dragon** [comment]
This was addressed with #899. You can adjust framerates to >60 values by going into the Graphics settings, change the "Refresh Rate" to "Custom", and the changing "Focus Active" to any desired value. Depending on your enviroment it would also be a good idea to adjust "Focus Inactive" to the same number.
Closing as complete.
