### ISSUE TITLE
source contains non-free font family Graphik

### ISSUE THREAD

**Issue by jonassmedegaard** [overte-org/overte#153]
Source contains multiple instances of the font family Graphik, which is copyright https://commercialtype.com/ and licensed only under a non-free license.

**Comment by ksuprynowicz** [comment]
Thanks!
We should remove it as soon as possible. Any suggestions for open fonts to replace it?

**Comment by daleglass** [comment]
It looks like a rather boring looking font: https://commercialtype.com/catalog/graphik

I think most anything else would do?

**Comment by ksuprynowicz** [comment]
Agreed. I suggest using one of the fonts we already have. Maybe Raleway?

**Comment by daleglass** [comment]
We have at a first glance:

* AnonymousPro
* Raleway
* Roboto
* Fira Sans
* Cairo (Semi-Bold only)

All those appear to be open

**Comment by ksuprynowicz** [comment]
AnonymousPro is fixed width, and the rest of them is very similar. I suggest Raleway, because it's already used in [hifi-style.css](https://github.com/overte-org/overte/blob/17b483284d98edbcf715651cea7b7c471dd363cf/scripts/system/html/css/hifi-style.css)

**Comment by ksuprynowicz** [comment]
Any of these is perfectly fine, but I need to know it very soon, because I'm working on opening a PR for it right now.

**Comment by daleglass** [comment]
I can do the PR if you want? Won't take long

**Comment by ksuprynowicz** [comment]
Awesome! I'd focus on rebasing scripting isolation PR then :)

**Comment by jonassmedegaard** [comment]
Beware that Graphik is referenced in quite a few places. :-(

In addition to [Raleway](https://www.theleagueofmoveabletype.com/raleway) this project also includes the derived [Rawline](https://fontlibrary.org/en/font/rawline):
> Rawline is nothing less than Raleway, with Lining Figures instead of OldStyle ones

Apparently Rawline is unmaintained, however (latest release in 2017 is based on Raleway 4.02, newest is Raleway 4.101).

[Cairo](https://gaber.design/cairo-free-font-family) has the benefit of covering arabic glyphs (it extends Titillum Web):
> Extending the famous Latin typeface family Titillum Web to support the Arabic script

**Comment by vegaslon** [comment]
looks like it is mostly just used in the simplified UI and the corporate launcher which no one currently uses.

**Comment by jonassmedegaard** [comment]
I recommend *against* replacing with AnonymousPro: Graphik is a relatively conservative-looking sans-serif font, whereas AnonymousPro is typewriter-style (and possibly, but as I recall not consistently, mono-spaced).

Among the ones already mentioned above, I recommend to replace with Fira Sans, due to being more similar in visual style.

**Comment by jonassmedegaard** [comment]
You guys are quick!

I see now that it was replaced with Raelway.  That font has a more opinionated style - assuming it was intentional to use another more conservative looking font, I guess a better choice (among those already included in the project) is Fira Sans (and there is no doubt even better choices if looking more widely among freely licensed fonts).

**Comment by daleglass** [comment]
Well, okay then! Here's an alternate version for testing.

**Comment by JulianGro** [comment]
Fixed by #155
