### ISSUE TITLE
Server stops working correctly after a few weeks

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#160]
After a few weeks server is stopping to work correctly. It fails to accept voxel editing messages, and fails to send entity messages to other players when voxel entities are being moved. I think it affects some other entities too.
Regular restart through web UI doesn't help, so it is possible that the problem is caused by assignment clients.
Shutting down and then starting again domain server and assignment clients temporarily fixes the issue.

**Comment by JulianGro** [comment]
Just FYI, you can kill the assignment clients one by one in the web UI and they will be restarted automatically.

**Comment by ksuprynowicz** [comment]
Thanks! I will try and see it it helps.
