### ISSUE TITLE
Cannot build Overte with VS2022

### ISSUE THREAD

**Issue by MarcusLlewellyn** [overte-org/overte#163]
While compiling dependencies with `vcpkg`, the `nvtt` package will not compile. Error log file is attached.
[install-x64-windows-rel-out.log](https://github.com/overte-org/overte/files/9332146/install-x64-windows-rel-out.log)

**Comment by JulianGro** [comment]
I am taking a look at this. We need to upgrade NVTT for macOS anyways.

**Comment by JulianGro** [comment]
@MarcusLlewellyn can you give confirm if https://github.com/overte-org/overte/pull/165 fixes your issue?
