### ISSUE TITLE
Rebranding issues

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#17]
This is an issue thread for any rebranding-related issues you encounter.
We still have to change names of executables, welcome text in tutorial world, links to API docs, and portal to the hub.
Post any problems you encounter here :)

**Comment by ksuprynowicz** [comment]
comment to test Discord Github integration

**Comment by ksuprynowicz** [comment]
I think we missed installer logo - it still shows Vircadia

**Comment by vegaslon** [comment]
need to update recompile https://github.com/overte-org/overte/tree/master/domain-server/resources/web/web-new/ so that the changes take effect

**Comment by AleziaKurdis** [comment]
> I think we missed installer logo - it still shows Vircadia

Addressed.

**Comment by AleziaKurdis** [comment]
tutorial and portal has been addressed too.

**Comment by AleziaKurdis** [comment]
This need to be fix:
![image](https://user-images.githubusercontent.com/60075796/155868158-793f34ba-9658-47ab-a7ca-7c7df9f4702d.png)

**Comment by akamicah** [comment]
I'm addressing the installer references to Vircadia in https://github.com/overte-org/overte/issues/36
