### ISSUE TITLE
Root bone added to GLB

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte#195]
When loading a GLB avatar, Interface *seems* to add some sort of root bone. However, I cannot confirm this; It is possible that Blender is in fact adding this extra bone.

To show what I am talking about:
In Interface there is an extra bone that seems to connect the object origin and the hip bone.
![overte-snap-by-JulianGro-on-2022-09-16_18-27-47_c](https://user-images.githubusercontent.com/11144627/190686678-d56845de-fd7f-48af-b835-9eadbf37ca77.png)

BabylonJS doesn't show this extra bone.
![Bildschirmfoto vom 2022-09-16 18-27-22_c](https://user-images.githubusercontent.com/11144627/190686866-15cec951-c1f4-4b2a-8649-d009f2b3f54f.png)

PlayCanvas on the other hand does show something similar to Interface. It displays a bone in the render, but this bone does not exist in the navigator on the left.
![Bildschirmfoto vom 2022-09-16 18-27-40_c](https://user-images.githubusercontent.com/11144627/190687630-a5d1f25e-9587-45c3-b1a0-e76d7e270557.png)

Blender does seem to remove bones that don't have any vertices attached to them, even though that seems to be disabled.

The GLB file is available here: https://data.moto9000.moe/m/Anon/FBX/Anon_Overte_10.glb

**Comment by SilverfishVR** [comment]
I think this is normal, The engine adds a bone at index "Armature" that goes from the base of support to the Hip bone. No idea why though.
For FBX it may add a similar one called "Mesh" if it works don't mess with it 🤷‍♂️ 

However, testing this I found some odd things. I am using blender, so your mileage may vary but Unless you specifically select what to include in the export (you should), other stuff in your scene like lights, cameras or empties will be included in the export. For FBX all of those are somehow interpreted as bone and thus included in your armature:

![InkedScreenshot 2022-09-16 215721](https://user-images.githubusercontent.com/53531160/190724357-bee55317-e6db-4905-bad0-786a00df4178.jpg)

Many of the default bookmarked avatars has lights and cameras included.
For GLTF, only empties seems to get included as bones.

**Comment by JulianGro** [comment]
Hmm. The reason I assumed it was a problem is that one of my models doesn't animate properly when it is a GLB. It increases the height of my model when running and flying.

**Comment by JulianGro** [comment]
I will close this, since the root bone being added isn't the actual problem.
