### ISSUE TITLE
No feedback on successful logon

### ISSUE THREAD

**Issue by Colorfingers** [overte-org/overte#200]
When in the interface and you select File -> Directory Service Logon/Signup the Logon In to Directory Service window opens.  When you successfully logon the Window provides no feedback that you have successfully logged on.  The title ribbon shows you are logged on and the file option changes indicating you are logged on. 

![image](https://user-images.githubusercontent.com/42556646/192108832-cff39835-ec9a-4c7e-a243-6337e81a50a1.png)

![image](https://user-images.githubusercontent.com/42556646/192108853-baa2c2ea-8214-481f-91c1-bb19f370bf32.png)

**Comment by JulianGro** [comment]
For reference, the window does stay open even on a successful login when being on a domain server; Not just on the tutorial serverless.
