### ISSUE TITLE
Infrequent crash when opening People app

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte#201]
When opening the People app, Interface sometimes crashes for me.
This has been happening at least on 2022.9.1-rc1 and rc2.

**Comment by daleglass** [comment]
Needs a backtrace

**Comment by JulianGro** [comment]
According to GDB, this isn't a crash.
It says that it "exited normally". The log doesn't give any hint either.

**Comment by ksuprynowicz** [comment]
I think this was related to XMLHttpRequest bug that was later fixed in V8. I didn't have it happen after fixing it but if it still does we should repoen.
