### ISSUE TITLE
non-free files below unpublishedScripts/marketplace/gameTable/assets/cards

### ISSUE THREAD

**Issue by jonassmedegaard** [overte-org/overte#213]
The file <unpublishedScripts/marketplace/gameTable/assets/cards/texture_accreditation.txt> contains this:
> One or more textures on this 3D model have been created with images from CGTextures.com. These images may not be redistributed by default, please visit www.cgtextures.com for more information.

I can only read that as the whole subdirectory needs to be removed (unless it can be identified which of the files are not redistributable).

**Comment by daleglass** [comment]
Thanks for the report, we'll look into this.
