### ISSUE TITLE
website is hosted both with and without leading www

### ISSUE THREAD

**Issue by jonassmedegaard** [overte-org/overte#218]
Websites https://www.overte.org/ and https://overte.org/ both exist and provide seemingly identical content.

This can negatively affect search-engine ranking.  I recommend to configure your web server to host only one of those, and have the other redirect permanently to it, e.g. like this using Apache2:
```
RedirectMatch permanent ^(?!/.well-known/acme-challenge/)(.*) https://${_HOST}$1
```

**Comment by jonassmedegaard** [comment]
Ah, from README.md it seems the no-www site is the canonical one. Bonus points for promoting that nice choice by a link to http://no-www.org/ ;-)

**Comment by JulianGro** [comment]
Yeah, the www is only there in case someone adds it when typing the url manually.
I guess a redirect makes more sense, since it tells people "you didn't have to type www"

**Comment by JulianGro** [comment]
Should be changed
