### ISSUE TITLE
Fix jumping overlay in VR

### ISSUE THREAD

**Issue by Kreolis** [overte-org/overte#227]
The whole overlay recenters itself when looking for a while in one direction. In combination with other windows this is annoying. 

Either bind it to the field of view or think of something else?

**Comment by Kreolis484** [comment]
Chat window could be pinnable to the wrist

**Comment by Kreolis484** [comment]
Maybe instead of parenting it to the head movement, one could try parenting it to the root bone

**Comment by Kreolis484** [comment]
Could the overlay be also enabled as an option in desktop mode?
