### ISSUE TITLE
Document where each part of the API applies (client, assignment client, etc)

### ISSUE THREAD

**Issue by OfficialR3ido101** [overte-org/overte#243]
I would be great for the API-documentation to get an update on what can run where whether its assignment client or normal client or server sided.

**Comment by JulianGro** [comment]
We have this for every namespace, as far as I can tell. 
![Auswahl_007](https://github.com/user-attachments/assets/6b8d8a87-6f20-44c8-a990-810560a7bd65)

Please reopen if I am misunderstanding.
