### ISSUE TITLE
Improvements to asset workflow and creation tools

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#253]
Place your ideas for improvements here :)

**Comment by AleziaKurdis** [comment]
Connecting the material entity from the object is no big deal programatically speaking. (Programatical usage is the main interest to use a material entity, and probable at the origin of their existence. Otherwise other alternative exists)
You would be forced to edit the object to connect a material to it. This means that you would need to edit it. The visitor who don't have the permission to edit when a client script is run will not be able to connect a generated material entities.  You would be systematically forced to used the server to do it. (adios serverless)
Maybe what you need is more a .fst generator feature.

**Comment by akamicah** [comment]
> We need a built-in asset browser, preferably with thumbnails. It would be used to select assets like models, materials or meshes in the URL fields in Create App, and would show assets available in Asset Browser and external repositories.

Expanding slightly after the dev discussion regarding asset repositories:

It'd be nice if we establish a standard for such repositories - tagging assets with information such as author, license, author website, either embedded in the assets (if the file file format allows arbitrary information to be stored), or by accompanying the asset with a json which the interface attempts to retrieve when pulling available assets from the repository.

Also from a user perspective, adding/removing repositories should be as simple as subscribing/unsubscribing to asset repositories, much like in Steam people can subscribe to Workshop items, and maybe have a master list kept on the metaverse server with a list of asset repositories to make it easier for users to find them, as well as give them the opportunity to add urls directly

**Comment by ksuprynowicz** [comment]
Refreshing/reloading assets should be made easier in the future.

**Comment by ksuprynowicz** [comment]
> External repositories... public ones ? I would always have hesitation to build anything base on something that I can't control and can disappears anytime. Maybe a repository from where you can transfer it to your asset server of download it (in order to store it where you want)

Good point. What I had in mind is automatic download of assets to the local asset server if they are in external public repository. This would also help a lot with the bandwidth costs of running such repository.

**Comment by ksuprynowicz** [comment]
It turns out that materials can already inherit from other materials and it is done just by pasting UUID in the material URL. That means that most of the improvements would be just modifications of create app. One thing that would be useful would be an API function to generate material entities from materials contained in an model file. In the future it would be nice to make FST files use JSON and then bake both FST file and entire model into a single file using Assimp.

**Comment by AleziaKurdis** [comment]
"One thing that would be useful would be an API function to generate material entities from materials contained in an model file."

I was to do that some time ago. But it can't work with model with embedded texture. (and sadly a lot of people use such embeded texture model)

**Comment by AleziaKurdis** [comment]
One problem the material entity has is the size of the material entity it-self.. if you want to plug a material entity on a very large model (many km wide), if you enter the domain next to this model, the material can be far enough and be too small to be loaded. So the model don't get the material set. (I have this case that can be seen in-world right now) We need to be able to scale the materiel entity to avoid this kind of issues.

**Comment by Armored-Dragon** [comment]
As this discussion has winded down, this issue will be closed and relevant topics will be made into their own issues.

If you have any more ideas, *please* feel free to make other issues!

Please see the following issues:
- https://github.com/overte-org/overte/issues/794
- https://github.com/overte-org/overte/issues/1145 (Material library)
- https://github.com/overte-org/overte/issues/1163 
- https://github.com/orgs/overte-org/projects/8?pane=issue&itemId=80933370 (Third party asset providers, this is planned with a rework to the Edit.js application)
