### ISSUE TITLE
Limit on the number of light sources in scene

### ISSUE THREAD

**Issue by Morgenstern29** [overte-org/overte#272]
We should pay attention to limiting the number of light sources in the scene. The limit is approximately 20 light sources. Users recommend tying light sources to visibility zones. This method works. In the future, you can think about how to remove the restriction in such a way that this does not affect performance. This problem is not critical and is described here for the attention of developers.

**Comment by JulianGro** [comment]
There is no known limit on light sources. The hub currently has >100 lights.
