### ISSUE TITLE
Remove Inventory & Marketplace option from Wearables GUI

### ISSUE THREAD

**Issue by akamicah** [overte-org/overte#275]
Avatar -> Adjust Wearables -> Get More -> Marketplace

![image](https://user-images.githubusercontent.com/10180011/206745874-2e8de8a5-a57e-49da-8aa0-7dd3f40e7bb9.png)

**Comment by akamicah** [comment]
The inventory too as it points to HiFi interface which has commerce entwined

![image](https://user-images.githubusercontent.com/10180011/206746433-c772910d-23cf-40b9-86b6-e9c652c527c3.png)

![image](https://user-images.githubusercontent.com/10180011/206746298-3ec6e5f1-2c6b-4f37-840b-7e03bd54710b.png)

**Comment by JulianGro** [comment]
The options have been removed.
The actual UIs are still in the code right now. If I remember, I will remove them in a later PR.
