### ISSUE TITLE
Resetting non-essential settings doesn't reset current avatar URL anymore

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#277]
If current avatar is crashing Interface, then on the next time Interface is started there's a prompt to reset all settings, or only non-essential ones. Previously resetting non-essential ones cleared current avatar URL, and now it doesn't do this. I think that clearing all settings doesn't clear it either, but it would need to be checked. This means Interface cannot bestarted at all.

**Comment by daleglass** [comment]
That might be my fault since I touched a lot of the settings system
