### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [overte-org/overte#287]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [AudioScope::freeScope](https://github.com/overte-org/overte/blob/17b483284d98edbcf715651cea7b7c471dd363cf/interface/src/audio/AudioScope.cpp#L111 "AudioScope::freeScope function")
- [ResourceImageItemRenderer::createFramebufferObject](https://github.com/overte-org/overte/blob/17b483284d98edbcf715651cea7b7c471dd363cf/interface/src/ui/ResourceImageItem.cpp#L120 "ResourceImageItemRenderer::createFramebufferObject function")
- [Wallet](https://github.com/overte-org/overte/blob/95ebe6bab0d5ff9707971f19051177110e274b3d/interface/src/commerce/Wallet.cpp#L345 "Destructor for Wallet")

**Comment by daleglass** [comment]
Sounds reasonable! Right now developer time is a bit scarce and we're busy with various big projects, so it may take us a while to get to this.

Feel free to submit a PR!

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by JulianGro** [comment]
Sounds interesting. I might look into that next year.
Right now we are just really busy.

**Comment by daleglass** [comment]
Probably! Have in mind that there are 400K lines of code, so there's a quite high likelihood of such a tool generating a lot of reports.

At that point it would be a cost/benefit issue. Sure, technically this is cleaner. Practically, it should make no difference but still expend time and effort. I think perhaps try to start looking for something that might be an actual bug.

**Comment by elfring** [comment]
:thought_balloon: Some implementation details can be automatically improved with [the help of advanced development tools](https://en.wikipedia.org/wiki/Code_refactoring#Automated_code_refactoring "Description of possibilities for code refactoring"), can't they?

**Comment by daleglass** [comment]
They can, yes, and we've done such work ourselves. Right now everyone is busy with big projects, though.

We welcome PRs from anybody, so if you feel like engaging in a cleaning up project, feel free to do so!
