### ISSUE TITLE
Fullscreen mode seems to always move window to main screen when there are multiple screens

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#298]
It's reported to happen on Windows and definitely happens on Debian Testing with Awesome WM. It's not a problem on Awesome WM, due to shortcut for moving window between screens, but it may cause trouble on Windows and on other window managers on Linux, so it's worth checking.

To replicate, move Overte window to secondary screen and then switch to full screen mode. The window will move to the primary screen on its own, while the desired behavior would be for it to stay on the screen where it was placed in windowed mode.

**Comment by CodeFreezr** [comment]
This prevents the use of Overte on a second "streaming" monitor. I have already tried various work-a-rounds, e.g. Changing the primary monitor in Windows, or launching the app from the streaming monitor.

If it is possible I would made it selectable on which Monitor you wanna the "Full Screen". If not direct beside "/Display/FullScreen" then perhaps as an Configuration-Option anywhere.

**Comment by daleglass** [comment]
Found the problem: There's a TODO, so somebody just needs to figure out how to get the current monitor and put it there.

https://github.com/overte-org/overte/blob/77ed7f85b9d60997a414d309cbe658a184c3853b/libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.cpp#L168-L171

**Comment by daleglass** [comment]
An interesting wrinkle: Under Wayland on Linux this function can't be implemented. Wayland considers that it's none of the application's business what exists or doesn't outside of the application itself, so the app can't make question of where it is on the screen, nor probably which screen it is on.

The solution I guess is just to give the user an option of which screen to use.

**Comment by CodeFreezr** [comment]
This would be the solution with the best control for the user.
