### ISSUE TITLE
Cameras app on more crahes on V8

### ISSUE THREAD

**Issue by Basinsky** [overte-org/overte#344]
I narrowed it down to:  MyAvatar.audioListenerMode = MyAvatar.audioListenerModeCustom; crashes interface

**Comment by ksuprynowicz** [comment]
Thanks!
I can confirm the crash. It seems to be due to a bug in ScriptVariantV8Proxy::unwrapQVariantPointer, so I should be able to fix it.

**Comment by ksuprynowicz** [comment]
Fixed!
