### ISSUE TITLE
[V8] desktop fargrabbing with the mouse does not work on grabbable entities

### ISSUE THREAD

**Issue by Basinsky** [overte-org/overte#345]

**Comment by SilverfishVR** [comment]
confirmed

**Comment by JulianGro** [comment]
Same on Linux actually.

**Comment by vegaslon** [comment]
Same with VR windows

**Comment by ksuprynowicz** [comment]
> Same with VR windows

Does VR mode in general work for you?
For me it immediately crashes and I still need to do a debugger run to figure out what is wrong.

**Comment by vegaslon** [comment]
Not immediately, does crash after a bit if I move too much.

**Comment by ksuprynowicz** [comment]
Fixed!
