### ISSUE TITLE
Identify and host/remove references to external dependencies

### ISSUE THREAD

**Issue by akamicah** [overte-org/overte#35]
References to resources that sit outside of git or a vendor server, and references to repos that sit inside Vircadia's git organisation still exist and need to be reviewed and a determination made if the references are needed/if we should fork into our own organisation.

Note: This list may not contain all

In `overte/hifi-qt.py`
- `http://motofckr9k.ddns.net/vircadia_packages/qt5-install-5.15.2-ubuntu-18.04-aarch64_test.tar.xz` [Line 164]
- `https://data.moto9000.moe/vircadia_packages/qt5-install-5.15.2-debian-10-aarch64.tar.xz` [Line 174]

~~In `overte/hifi-android.py`~~
~~`https://cdn-1.vircadia.com/eu-c-1/vircadia-public/dependencies/android/` [Line 13]~~

~~In `overte/android/build.gradle`~~
~~`https://cdn-1.vircadia.com/eu-c-1/vircadia-public/dependencies/android/` [Line 51]~~

~~In `overte/android/setupGVR.gradle`~~
~~`https://cdn-1.vircadia.com/eu-c-1/vircadia-public/austin/android/`~~

~~In `overte/tools/ci-scripts/upload_to_publish_server.py`~~
~~`build-uploader.vircadia.com` [Line 44]~~

In `overte/tools/nitpick/AppDataHighFidelity/Interface.json`
- `https://cdn-1.vircadia.com/eu-c-1/vircadia-public/sounds/Collisions-otherorganic/Body_Hits_Impact.wav` [Line 41]

~~In `overte/tools/qt-builder/qt-lite-build-steps.md`~~
~~`https://cdn-1.vircadia.com/eu-c-1/vircadia-public/dante/ssl-static-windows.zip` [Line 33]~~
~~`https://cdn-1.vircadia.com/eu-c-1/vircadia-public/dante/openssl-static-osx.zip` [Line 74]~~

In `overte/scripts/defaultScript.js`
~~`https://cdn.vircadia.com/community-apps/more/app-more.js` [Line 49]~~
- `https://content.fluffy.ws/scripts/chat/FloofChat.js` [Line 50]

In `overte/scripts/system/html/users.html`
- `https://cdn-1.vircadia.com/eu-c-1/vircadia-public/faye/tablet-dev/refresh-icon.svg` [Line 255] (unused and outdated)

~~In `overte/scripts/system/more/app-more.js`~~
~~`https://cdn.vircadia.com/community-apps/applications` [Line 59]~~

~~In `overte/scripts/system/more/more.html`~~
~~`https://cdn.vircadia.com/community-apps/applications/metadata.js` [Line 57]~~
~~`https://cdn.vircadia.com/community-apps/applications/` [Line 67]~~
~~`https://cdn.vircadia.com/community-apps/web/index.html` [Line 171]~~

~~In `overte/scripts/system/places/places.js`~~
~~`https://metaverse.vircadia.com/interim/d-goto/app/goto.json` [Line 386]~~

~~In `overte/scripts/system/quickGoto.js`~~
~~`lq-hub.vircadia.com` [Line 34]~~

References to repos in Vircadia org:
~~`vircadia/draco` (In `cmake/ports/draco/portfile.cmake`)~~
~~`vircadia/etc2comp` (In `cmake/ports/etc2comp/portfile.cmake`)~~
~~`vircadia/scribe` (In `cmake/ports/hifi-scribe/portfile.cmake`)~~
~~`vircadia/nvidia-texture-tools` (In `cmake/ports/nvtt/portfile.cmake`)~~

**Comment by JulianGro** [comment]
In overte/hifi-qt.py: Those Qt files are for aarch64 only and are not actually used. They are hosted on my home server for any tinkerers, but we can also remove them. Times have changed and they aren't needed anymore.

In overte/tools/ci-scripts/upload_to_publish_server.py: that is being addressed by https://github.com/overte-org/overte/pull/39
