### ISSUE TITLE
V8 branch crashes when there's no interface.json file

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#352]

**Comment by AleziaKurdis** [comment]
Step: 
On a V8 build installation, remove the "interface.json" from the AppData/Toaming/Overte
Start Interface... it will crashes (but it will have restored a default "interface.json" file
Start again, it works.

In previous build, it was starting using the new created "interface.json".

**Comment by ksuprynowicz** [comment]
I tested it with the newest version on Linux and it's fixed there. I still need to test it on Windows.

**Comment by daleglass** [comment]
Tested after #445, no crash for me.
