### ISSUE TITLE
"grab move stick" no longer shows in V8

### ISSUE THREAD

**Issue by SilverfishVR** [overte-org/overte#369]
In the V8 build (2023.03..24.v8-) the "stick" that would usually show in the middle of objects being grab moved (desktop) no longer shows.
![Screenshot 2023-04-01 00 33 59](https://user-images.githubusercontent.com/53531160/229245306-e1739c9d-ae76-4c12-96b6-a3aba3ce91f8.png)

**Comment by JulianGro** [comment]
It works for me and I haven't seen it not work in the past.
Even when you couldn't move objects in V8, I would still always see the "stick".

**Comment by SilverfishVR** [comment]
I will re-test

**Comment by ksuprynowicz** [comment]
It's fixed in newest V8 build.
