### ISSUE TITLE
Laser pointer blinking when fully pressed

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#406]

**Comment by ksuprynowicz** [comment]
It's also reported that it triggers haptics.

**Comment by vegaslon** [comment]
the laser pointer is not so much blinking as it is constantly clicking instead of clicking and holding when held. This is causing the blinking behavior and leaving the pointer with out the opportunity to turn red to denote it is not touching anything.

**Comment by vegaslon** [comment]
This behavior also makes it really hard to scroll setting menus in vr.

**Comment by ksuprynowicz** [comment]
Fixed!
