### ISSUE TITLE
Crash on V8 assignment client on Debian Stable

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#432]
Debian Stable has wrong node.js version so the prebuilt one for Ubuntu 18.04 is used.
```Thread 1 "assignment-clie" received signal SIGSEGV, Segmentation fault.
0x00007ffff2d7a50f in ssl_create_cipher_list () from /home/v8/overte-files/vcpkg/f0278369/installed/x64-linux/lib/libnode.so.108
(gdb) bt
#0  0x00007ffff2d7a50f in ssl_create_cipher_list () from /home/v8/overte-files/vcpkg/f0278369/installed/x64-linux/lib/libnode.so.108
#1  0x00007ffff2d8150b in SSL_CTX_set_cipher_list () from /home/v8/overte-files/vcpkg/f0278369/installed/x64-linux/lib/libnode.so.108
#2  0x00007ffff2d7b5b0 in cmd_CipherString () from /home/v8/overte-files/vcpkg/f0278369/installed/x64-linux/lib/libnode.so.108
#3  0x00007ffff2d7c470 in SSL_CONF_cmd () from /home/v8/overte-files/vcpkg/f0278369/installed/x64-linux/lib/libnode.so.108
#4  0x00007fffefcf1b02 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#5  0x00007fffefced25d in SSL_CTX_new () from /lib/x86_64-linux-gnu/libssl.so.1.1
#6  0x00007ffff7665263 in ?? () from /lib/x86_64-linux-gnu/libQt5Network.so.5
#7  0x00007ffff7666311 in ?? () from /lib/x86_64-linux-gnu/libQt5Network.so.5
#8  0x00007ffff7648aef in ?? () from /lib/x86_64-linux-gnu/libQt5Network.so.5
#9  0x00007ffff764166e in QSslConfiguration::defaultConfiguration() () from /lib/x86_64-linux-gnu/libQt5Network.so.5
#10 0x00007ffff75a66c7 in QNetworkRequest::sslConfiguration() const () from /lib/x86_64-linux-gnu/libQt5Network.so.5
#11 0x00007ffff75f8f90 in ?? () from /lib/x86_64-linux-gnu/libQt5Network.so.5
#12 0x00007ffff7599df4 in QNetworkAccessManager::createRequest(QNetworkAccessManager::Operation, QNetworkRequest const&, QIODevice*) () from /lib/x86_64-linux-gnu/libQt5Network.so.5
#13 0x00007ffff7598715 in QNetworkAccessManager::get(QNetworkRequest const&) () from /lib/x86_64-linux-gnu/libQt5Network.so.5
#14 0x00007ffff062f182 in AccountManager::sendRequest (this=this@entry=0x55555592f070, path=..., authType=<optimized out>, operation=<optimized out>, callbackParams=..., dataByteArray=..., dataMultiPart=<optimized out>, propertyMap=...) at /home/v8/overte/libraries/networking/src/AccountManager.cpp:306
#15 0x00007ffff061e34d in AccountManager::qt_static_metacall (_o=0x55555592f070, _c=<optimized out>, _id=<optimized out>, _a=0x7fffd4007530) at /home/v8/overte/build/libraries/networking/networking_autogen/UVLADIE3JM/moc_AccountManager.cpp:306
#16 0x00007ffff12dbff1 in QObject::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff12aff9f in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff12b2a01 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff1307e93 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007fffeeb2de6b in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007fffeeb2e118 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007fffeeb2e1cf in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff130751f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff12ae98b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff12b6c00 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00005555555b0bb8 in main (argc=3, argv=0x7fffffffe5a8) at /home/v8/overte/assignment-client/src/main.cpp:22
```

**Comment by daleglass** [comment]
This may be some sort of linking issue. It's possible libnode is linking against one version, while we're linking to another.

One thing that needs investigating is building libnode in such a way that OpenSSL symbols are not exposed to the outside. Another is an upgrade to the latest OpenSSL.

This is best looked into after #381.

That PR is going to drop a lot of calls to unusual OpenSSL functions, which makes it less troublesome to upgrade to a newer OpenSSL -- which we should anyway, for good security reasons.

**Comment by daleglass** [comment]
Okay, so this is weird.

1. We start in AccountManager, and make an https request.
2. This goes through Qt, makes sense so far.
3. Qt talks to the system OpenSSL, that also makes sense
4. Somehow from OpenSSL we call into libnode.so (!!!)


Part 4 definitely shouldn't be happening. It appears we have a linking issue here. libnode.so includes OpenSSL inside it, and that mixes the linker up somehow.

So it occurs to me there are 3 ways to go here:

1. Make sure libnode.so doesn't export OpenSSL symbols
2. Make sure the linker gives the system OpenSSL priority somehow.
3. Make libnode.sso use an external OpenSSL library

**Comment by ksuprynowicz** [comment]
Maybe building libnode with shared OpenSSL would help?
```
shared_optgroup.add_argument('--shared-openssl',
    action='store_true',
    dest='shared_openssl',
    default=None,
    help='link to a shared OpenSSl DLL instead of static linking')
    ```

**Comment by ksuprynowicz** [comment]
I'm really stuck on this and I don't think I can figure it on my own. The issue is that prebuilt Node.js uses it's own OpenSSL.
We cannot supply prebuilt Node.js without knowing which OpenSSL version will be used by system Qt of a given distribution.
I think the only way to figure this out would be building Node.js from source (with --shared-openssl flag) if system Qt is used but there's no system Node.js, but I have no idea how to do this conditionally.
I think I will try modifying vcpkg file so that it builds Node.js on Linux. Then it can use same version of OpenSSL as Qt.

**Comment by JulianGro** [comment]
We ship our own OpenSSL, so why not just build against that?

**Comment by ksuprynowicz** [comment]
When we use prebuilt Qt it's indeed the best option, but when we use system Qt it's likned against different version of OpenSSL on each distro.

**Comment by ksuprynowicz** [comment]
So the problem happens on distros that have no prebuilt Qt available for them but have different Node.js version than 18.

**Comment by JulianGro** [comment]
> When we use prebuilt Qt it's indeed the best option, but when we use system Qt it's likned against different version of OpenSSL on each distro.

Looking closer, we don't seem to actually use the OpenSSL that we provide via VCPKG outside of Windows, even though there is a version specific to Linux. So my assumption that we always include OpenSSL was wrong.

**Comment by JulianGro** [comment]
Is this still a problem after switching to having VCPKG build node from source?

**Comment by ksuprynowicz** [comment]
I'm pretty sure this should be fixed now. Should we close it?

**Comment by JulianGro** [comment]
Lets just reopen if if happens again.
