### ISSUE TITLE
[v8] noise gate indicator not working

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte#434]
When the noise gate is closed (there is no microphone input being sent), the microphone indicator is supposed to change to a blue one. On v8 this is currently broken.
See:
![Auswahl_085](https://github.com/overte-org/overte/assets/11144627/cc95f918-f54c-498e-835f-6af6a05cf57b)

**Comment by shocktail39** [comment]
found the problem file, working on fix

**Comment by shocktail39** [comment]
the lines that cause this were purposely commented out, saying it was causing an error.  i wasn't able to recreate this error, but i would appreciate some mild testing just in case.
