### ISSUE TITLE
scripting console autocomplete does not work

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte#451]
The scripting console is supposed to have an autocomplete function, but I have never seen it in my three years of using this platform.

Supposedly it worked on Windows in Vircadia before, but I have no idea if that is actually the case.

**Comment by SilverfishVR** [comment]
It sure did, sometimes it was very janky but it did do autocomplete suggestions for the API.

**Comment by ksuprynowicz** [comment]
It does work correctly, cmake just needs this command line option:
```
-DJSDOC_ENABLED:BOOL=TRUE
```
