### ISSUE TITLE
Thumbsticks need to be pressed to move

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#459]
This happens on many headsets accessed through Steam VR, for example Reverb G2 and Pico 4.

**Comment by ksuprynowicz** [comment]
https://github.com/overte-org/overte/blob/758d98a3977f9ebc836783c933a4b43ac47bc078/interface/resources/controllers/vive.json#LL13C133-L13C133

**Comment by JulianGro** [comment]
This has the "fix before release" label, but there doesn't seem to be a proper way to fix this without switching to a system that allows us to provide different mappings. Which would be another substantial change, wouldn't it?

**Comment by ksuprynowicz** [comment]
Maybe there's some stopgap issue, like for example adding an option to settings?

**Comment by SilverfishVR** [comment]
or maybe, change the default mapping so that the Vive wands are the controllers that don't quite work well, but make a controller script that users of those, if any, can load.
