### ISSUE TITLE
Add FOV adjustment to graphics menu

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#460]
Add FOV setting slider - on current FOV it's very difficult to use Create App in first person mode.

**Comment by SilverfishVR** [comment]
I think maybe 2 different settings for VR & desktop.
I VR there is already the `HMD.ipdScale` that may need to be taken into account when changing FOV.

**Comment by ksuprynowicz** [comment]
Right now I will only try to add a setting for Desktop mode

**Comment by ksuprynowicz** [comment]
Implemented in https://github.com/overte-org/overte/pull/465
