### ISSUE TITLE
Announcements don't respect new window size

### ISSUE THREAD

**Issue by rampa3** [overte-org/overte#470]
When you resize Overte interface's window, the announcements system ignores new window size for its coordinates system. Because of this, announcements are displayed either off-screen or closer to the center of screen, until the interface is restarted, On restart, the coordinates for the announcements sync to the window size, up until another resize.

**Comment by rampa3** [comment]
Update: When messing with latest release, I found out the announcements acknowledge new window height when changing window size, but ignore window width change. The bug is present only in accomodating new width in their positioning.

**Comment by Armored-Dragon** [comment]
This was fixed with #831. Closing as complete.

**Comment by rampa3** [comment]
@Armored-Dragon > This was fixed with #831. Closing as complete.

Should this be in RC2? I booted up RC2 and it still ignores window width. Announcements is the JS API endpoint for showing the toast notifications on top right of the window. `Window.displayAnnouncement` is what I used in the mouse look script.

**Comment by Armored-Dragon** [comment]
Yes, this should be in the newest release candidate. The announcement position is updated every time an announcement is made, [see here](https://github.com/overte-org/overte/blob/09e5a60c8ba76ef9a5d3a71b163f90dbd721a176/scripts/system/notifications.js#L90). If there are any existing announcements when you resize your window their position will be different than what is expected. 
When a new announcement is made, is your announcement area not being properly updated?

**Comment by rampa3** [comment]
> Yes, this should be in the newest release candidate. The announcement position is updated every time an announcement is made, [see here](https://github.com/overte-org/overte/blob/09e5a60c8ba76ef9a5d3a71b163f90dbd721a176/scripts/system/notifications.js#L90). If there are any existing announcements when you resize your window their position will be different than what is expected. When a new announcement is made, is your announcement area not being properly updated?

OK, it works. I did test only by resizing with old ones on screen, since in case of height change they react during the change, and I thought that is how it would work here too. But yes, when new one appears/one disappears to trigger an update, they snap where they belong.
