### ISSUE TITLE
create menu list empty

### ISSUE THREAD

**Issue by shocktail39** [overte-org/overte#475]
![screenshot of bug](https://github.com/overte-org/overte/assets/6035079/4983ec4b-b9fa-4efb-b79d-2c2b76d56059)

this is happening to me in every world, desktop or vr.

**Comment by AleziaKurdis** [comment]
What is this W logo ?

**Comment by JulianGro** [comment]
> What is this W logo ?

Probably not what you think.
I assume it comes from some sort of X11 to Wayland compatibility layer.

**Comment by ksuprynowicz** [comment]
Fixed by https://github.com/overte-org/overte/pull/477
