### ISSUE TITLE
Unable to import JSON with "renderWithZones" on v8 domain-server

### ISSUE THREAD

**Issue by keeshii** [overte-org/overte#494]
Importing the JSON that contains an entity with "renderWithZones" fails with the following errors in the server's console:

```
[06/29 10:28:19] [CRITICAL] [overte.scriptengine.v8] [23] [entity-script-server] Parameter  0 in method  DebugDraw :: "drawRays"  is of type QMetaType::UnknownType
```

**Steps to reproduce**:
1. Connect to a V8 Server (the issue is not happening on the QtScript/domain-less server)
2. Use "*Edit > Import Entites from a File*" to import the JSON ([zone.test.zip](https://github.com/overte-org/overte/files/11904808/zone.test.zip)).

**Results**:
After about 5~10 seconds after the import, the server reports critical errors and imported entities dissapears.

**Expected results**:
Import to be completed successfully wihout any errors.

**Comment by JulianGro** [comment]
I cannot reproduce the issue.
How did you get your hands on a v8 server? Did you build from source? What distribution are you on?

**Comment by keeshii** [comment]
The v8 server was build in the docker-container. The system used for build is ubuntu 20. My Dockerfile is slighty modified version of the Misterblue/vircadia-domain-server-docker, so it is using overte-builder, etc. I will check, if I can still reproduce the issue on current master. If so, I will provide more detailed steps.

**Comment by keeshii** [comment]
I also can't reproduce the issue on the current master. I am really curious when it happend. As far as I know, bugs don't just disappear. Anyway, I think the thread can be closed.
