### ISSUE TITLE
log in developer menu slow to open

### ISSUE THREAD

**Issue by vegaslon** [overte-org/overte#496]
when you go to developer menu and click the log is is slow to open and almost crashes client on windows

**Comment by JulianGro** [comment]
This is most likely an oversight in https://github.com/overte-org/overte/pull/342

Our log viewer probably cannot handle files of this size.
The old behaviour was most likely only showing the most recent log file, so to prevent long loading  we could load only the last 512 KiB which would presumably be the limit of what the log viewer would have been able to show in the past.
