### ISSUE TITLE
Interface crash on a script

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#497]
Thanks to Armored Dragon for finding this issue!
https://github.com/Armored-Dragon/overte-app-examples/blob/master/crasher-1/_crasher1.js

**Comment by ksuprynowicz** [comment]
It doesn't seem to happen on newest Linux build. I will have to try on Windows too.

**Comment by JulianGro** [comment]
Doesn't crash me on 2023.10.1-rc5, 74 also says that they don't crash.
