### ISSUE TITLE
Create menu search does not work in latest master

### ISSUE THREAD

**Issue by SilverfishVR** [overte-org/overte#502]
Not sure when it broke but the search bar in the entity list no longer filters the results as you type.
If you close and reopen create it will show an empty list even if the search term matches entities in the domain.
If there is anything in the search field, The other filters (visible, entity type) don't work.

* open create menu and type something in the search bar, the entity list does not update.
* close and reopen create, the search term persists but the entity list is empty, even if there should be matches.
* clear search field, close and reopen create, type something in the search bar. the entity type dropdown and "visible" button does not filter the list anymore.

Tested on Win10 Build 181-9ded209

**Comment by ksuprynowicz** [comment]
Thanks!
Luckily there's an error message so it should be pretty easy to fix:
`[overte.scriptengine.script] [defaultScripts.js] entityList.js: Error parsing JSON`
I'll give it a try tomorrow.
