### ISSUE TITLE
Snap app doesn't hide UI anymore when taking a screenshot

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#504]
![overte-snap-by-X74hc595-on-2023-07-03_18-46-27](https://github.com/overte-org/overte/assets/11568651/f8911a8e-f031-4d79-8f68-cb1b78730969)

**Comment by daleglass** [comment]
Dev meeting: Can't reproduce, Julian also says he can't

**Comment by daleglass** [comment]
Maybe a timing problem?

**Comment by JulianGro** [comment]
I mixed things up. I *can* reproduce it.
If I open the app and press the red button, it doesn't hide the UI while taking a screenshot.

**Comment by AleziaKurdis** [comment]
Th script use this to hide and show the Overlays.
    Menu.setIsOptionChecked("Show Overlays", true);

If we do this manually (menu  "Developer > UI > Show Overlays")
the toolbar and the app window doesn't hide. 
I supposed that it's the function that doesn't work anymore.
