### ISSUE TITLE
the create app entity list shows undefined for all entities

### ISSUE THREAD

**Issue by Basinsky** [overte-org/overte#505]
This is on Build 181-9ded209. If you look in the properties everything is correct. If you look in the entity list all URL's are undefined. Maybe this is a new security system? Then maybe use *** instead. 

![image](https://github.com/overte-org/overte/assets/51274563/d67dc6f9-8e20-4725-8ea8-0c2c553ef7e6)

![image](https://github.com/overte-org/overte/assets/51274563/e120e84c-e6c0-4ea3-aae8-f41e277e3566)

**Comment by ksuprynowicz** [comment]
I will have a look at this and 502 right now
