### ISSUE TITLE
Valve Index Controllers: trackpads annoyingly behave as the thumbsticks.

### ISSUE THREAD

**Issue by AleziaKurdis** [overte-org/overte#509]
Valve Index Controller: 

![image](https://github.com/overte-org/overte/assets/60075796/41144537-5028-4fca-8c7d-f6c1b17240e4)

Before the last build, the track button was use only to move down the avatar thumb.

With the last CR build,  the track button is also behaving as the thumbstick. (which is clearly not efficient for that purpose... the surface being not enough wide for that use. )
This is a bit annoying since this track button is very reactive and a bad move get triggerred when not really expected. (Litterally, it is border to do inconsistent  move since this is too small for that.

Note that the thumbsticks are still working fine.

I understood that some change might have been done for other type of controller, ideally, if we can't do a fix specifically for Valve Index, I would l like to be able to switch off that behavior. (maybe with a setting)

**Comment by SilverfishVR** [comment]
I agree that the trackpad should not act as thumbstick input, very annoying. 

But I am confident that this was always the case, I still use a steamVR controller mapping I made in 2020 that disables thumbpad when running "Interface" for that reason.
Mine still works, but perhaps your setup is different and something broke with the changes to controller mapping?

And on a side note, if the index mapping is open for updates, it would be nice to add a lot more deadzone to the Right stick up/down (`Controller.Hardware.Vive.RY` I think).
It is mapped to teleport (up) but when flying it stops you dead when trying to turn if you don't move the stick perfectly left/right.
I personally have it mapped to fly up/down with a 0.3 deadzone but some people might be weird and like to have teleport 😆

**Comment by JulianGro** [comment]
I just tested this on Windows and it is indeed a regression.
On v2022.12.1 the left trackpad needs to be pressed down for it to move you. On current master it reacts without pressing.
The left analog stick works without pressing down on it in both versions.
