### ISSUE TITLE
Places App: Clicking on a Place, and clicking on a Places "Visit" button connect differently

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte#514]
Clicking on the name of a Place connects to its IP, while clicking on "Visit" connects to the Place name.
You can see this in Overte's window title. Clicking on the Place name shows the IP of the place in the window title, while clicking on the "Visit" button makes it show the Place name in the window title.

**Comment by AleziaKurdis** [comment]
That's not exactly what happen I think....

if the place is on the local directory service, then it will use the place name to establish connection. 
if the place is not local (federated or external) then it used instead the ip:port to connect (cause the name would not be resolved , being not connected to those directory server)

I checked in the code, and both: place in the list and place detail (visit button) is doing this same thing.

Please retest making sure that you are comparing based on the directory server of the places. (local, federated, external)

But it is possible that the address in the bar (and also the address in the footer of the place app) could be not always resolved with the placename. (This is api side if it is the case.)

**Comment by JulianGro** [comment]
I have been comparing the Overte Hub to the Overte Hub.

But yeah, I guess I will have to take a look at the code then.

**Comment by AleziaKurdis** [comment]
Found the issue, there are 2 links in the list... one on the cell background and one on the placename... it'S the place name that is still using the address directly instead of the variable that know what to use.
I will fixed this soon.
