### ISSUE TITLE
script crashes interface 

### ISSUE THREAD

**Issue by SilverfishVR** [overte-org/overte#524]
This is related to PR #521

The script I use on the Stalebot avatar crashes interface if you stop it.

I have narrowed it down to the controller mapping part, specifically disabling a mapping. Here is a very stripped down version of the script: http://silverfish-freestuff.s3.amazonaws.com/TestStuff/PR521/test_scriptEnd_withDisableMapping.js

I thought it might be the `Script.scriptEnding` callback but it still crashes if I remove that, maybe the mapping object is destroyed before it is disabled 🤷‍♂️

It works in V8_RC2

**Comment by JulianGro** [comment]
In case someone other than 74 wants to work on it. This is most likely related to a change in the script engine shutdown procedure which was done in PR #521.
Funny enough, it actually has a comment worrying about a potential crash. https://github.com/overte-org/overte/blob/master/interface/src/Application.cpp#L7560C13-L7560C140

**Comment by ksuprynowicz** [comment]
It seems that shutdown rewrite fixed it.
