### ISSUE TITLE
Add a way to close the game more easily while in VR

### ISSUE THREAD

**Issue by jae1911** [overte-org/overte#537]
When doing VR sessions, it would be nice to have an easier way of leaving the game without having to walk to the computer and do either CTRL+Q or clicking the button in File.

Maybe adding a button on the tablet for that would be nice (with confirmation of course).

**Comment by ksuprynowicz** [comment]
Right now you can exit game from tablet by clicking Menu->File->Quit.

**Comment by jae1911** [comment]
Oh, my bad then.

**Comment by JulianGro** [comment]
Also don't forget that every runtime should have a way to quit the application. SteamVR and Oculus Home for example can quit Overte.
