### ISSUE TITLE
Assignment client in Overte Hub is leaking memory

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#538]
After a day or so it gets as high as 5 GB. This doesn't seem to affect other domains hosted on the same server so it's probably script engine-related.
A proper course of action for diagnosing this would be enabling memory reporting for script engines on entity server. For a more detailed report V8 can be built with additional flags.

**Comment by ksuprynowicz** [comment]
This may be caused by entities described in https://github.com/overte-org/overte/issues/661
After fixing that issue we need to check again.

**Comment by ksuprynowicz** [comment]
It turns out it's the entity server that is leaking memory and not entity script server.

**Comment by daleglass** [comment]
I'll try and see if there's some sort of additional stats we can get from the entity server to see what it might be

**Comment by ksuprynowicz** [comment]
It looks like the leak is caused by script engines being spawned and deleted all the time by EntityTree::writeToJSON and EntityTree::readFromMap. Long-term fix would be fixing leaks in repeatedly spawned and deleted script engines, but short term fix would be just creating single script engine together with the entity tree and using this script. This should be a pretty easy fix.
