### ISSUE TITLE
unculled backfaces don't throw shadows

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte#547]
When a model had backface culling disabled, that backface doesn't seem to throw a shadow.

![overte-snap-by-JulianGro-on-2023-08-04_14-01-32](https://github.com/overte-org/overte/assets/11144627/1e343ab9-e745-405e-9ea9-540d371cf43a)

**Comment by HifiExperiments** [comment]
I just tested this quickly with the "Material Data Creator" from the More app.  it creates a cube with the material applied and you can toggle the backface culling near the bottom.  all three modes seem to cast shadows correctly.  also just generally I'd expect this to work.  does this still reproduce?  perhaps it's related to the texture with opacity specifically?

**Comment by HifiExperiments** [comment]
ah!  ok, thank you!  I see the problem:

in `RenderShadowTask::build` we force the state to CULL_BACK:

```
        auto state = std::make_shared<gpu::State>();
        state->setCullMode(gpu::State::CULL_BACK);
        state->setDepthTest(true, true, gpu::LESS_EQUAL);

        auto fadeEffect = DependencyManager::get<FadeEffect>();
        initZPassPipelines(*shapePlumber, state, fadeEffect->getBatchSetter(), fadeEffect->getItemUniformSetter());
```

as opposed to `initForwardPipelines`/`initDeferredPipelines` which properly set up pipelines for all possible culling modes in `addPlumberPipeline`
