### ISSUE TITLE
Grabbing local entities doesn't work in VR?

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#565]
Reported by Alezia:
The ungrab issue is with the local entities. To reproduce, just grab the demo entity in the app: material data creator.

**Comment by AnotherFoxGuy** [comment]
I can also reproduce this issue, it also happens with the mirror app
You can grab the mirror but not release it and the only way to get it to detach is to disable the mirror

**Comment by ksuprynowicz** [comment]
Thanks!
This should be pretty simple to fix. I'll give it a try in about 8 days form now when I have access to a VR headset.

**Comment by ksuprynowicz** [comment]
I just checked it and keyboard doesn't seem to use MyAvatar.grab/releaseGrab at all. It seems to use some entirely different methods, which is very weird.
