### ISSUE TITLE
Text entity display breaks if content overflows entity dimensions

### ISSUE THREAD

**Issue by Zetaphor** [overte-org/overte#583]
If the text content of a text entity is longer than the text entity the text just fails to render, instead of overflowing and clipping.

Example:
![image](https://github.com/overte-org/overte/assets/3112763/5973693f-0713-4436-b93d-a36b77cfc1c6)

Add another character (content should be "aaaaaa"):
![image](https://github.com/overte-org/overte/assets/3112763/698d7e4c-83c3-4e6d-8913-0fe7d890e0f4)

Exported test entity:

```json
{
  "DataVersion": 0,
  "Entities": [
    {
    "id": "{895ad5d1-2f7f-42c1-a115-66c11f69806a}",
    "type": "Text",
    "lastEdited": 1692549024403436,
    "name": "Breaking text demo",
    "dimensions": {
        "x": 0.6499999761581421,
        "y": 0.5,
        "z": 0.009999999776482582
    },
    "rotation": {
        "x": -0.0000457763671875,
        "y": -0.9981689453125,
        "z": -0.0000152587890625,
        "w": 0.060715675354003906
    },
    "created": 1692548197153729,
    "lastEditedBy": "{01e4625a-ead3-4d8f-987b-36508edfa8a2}",
    "queryAACube": {
        "x": -0.41006097197532654,
        "y": -0.41006097197532654,
        "z": -0.41006097197532654,
        "scale": 0.8201219439506531
    },
    "grab": {
        "grabbable": false,
        "equippableLeftRotation": {
            "x": -0.0000152587890625,
            "y": -0.0000152587890625,
            "z": -0.0000152587890625,
            "w": 1
        },
        "equippableRightRotation": {
            "x": -0.0000152587890625,
            "y": -0.0000152587890625,
            "z": -0.0000152587890625,
            "w": 1
        }
    },
    "damping": 0,
    "angularDamping": 0,
    "text": "aaaaaa",
    "lineHeight": 0.2409999966621399,
    "textColor": {
        "red": 0,
        "green": 255,
        "blue": 55
    },
    "textEffect": "outline fill",
    "textEffectColor": {
        "red": 212,
        "green": 66,
        "blue": 212
    },
    "textEffectThickness": 0.47999998927116394,
    "alignment": "center",
    "clientOnly": false,
    "avatarEntity": false,
    "localEntity": false,
    "faceCamera": false,
    "isFacingAvatar": false
}
    ],
  "Id": "{6540433f-928f-4d40-83d6-f6400164c5c7}",
  "Version": 133
}
```

**Comment by AleziaKurdis** [comment]
Not really a bug, but more an enhancement request. (Since this is the current behavior since day 0)

I agree, it always been a bit annoying.

**Comment by Zetaphor** [comment]
I understand it may have been historically broken, but I'd still call that broken and thus a bug. Semantics aside, it's a very jarring behavior. 

I only discovered it through experimentation, initially I thought the text entity was just non-functional broken as I started by entering text that was too large for the dimensions.

**Comment by AleziaKurdis** [comment]
It's precisely what I meant by "a bit annoying." ;-)
it doesn't help new peole.

**Comment by vegaslon** [comment]
The original solution for this was to use https://apidocs.overte.org/Entities.html#.textSize

**Comment by keeshii** [comment]
The other behavior that is annoying is auto-trim. If we set text

"

   Abc

"

It is automatically transformed into "Abc". But not sure if it is a good idea to change any of that.

**Comment by AleziaKurdis** [comment]
You might need \n to force those lines.
