### ISSUE TITLE
setting joint data by name does not work

### ISSUE THREAD

**Issue by SilverfishVR** [overte-org/overte#613]
The API calls in [Avatar](https://apidocs.overte.org/Avatar.html) and [MyAvatar](https://apidocs.overte.org/MyAvatar.html) for:
[setJointData](https://apidocs.overte.org/Avatar.html#.setJointData)
[setJointRotation](https://apidocs.overte.org/Avatar.html#.setJointRotation)
[setJointTranslation](https://apidocs.overte.org/Avatar.html#.setJointTranslation)
Are overloaded to take either a joint name or a joint index, using a joint name does not work.

I remember having this issue back when I started in hifi some 800 years ago and I was sure it was fixed, but I just used joint index consistently since so I'm not really sure.

Tested on Win10 using 2023.07.1-rc3

**Comment by JulianGro** [comment]
Appears to still be an issue.
