### ISSUE TITLE
Some Tablet Apps Do Not Render Using AppImage.

### ISSUE THREAD

**Issue by Penguin-Guru** [overte-org/overte#63]
I compiled Overte and that version does not have this issue. Clearing caches and reloading scripts did not solve the problem.

Apps that render: Audio, Avatar, People, Graphics.

Apps that do not render: Snap, Places, Emote, Appreciate, More..., Chat.

Overte version: Overte-x86_64-20220226.AppImage
Linux version: 5.15.26 (Gentoo)

**Comment by ksuprynowicz** [comment]
You should add Linux distribution and version to the report.

**Comment by daleglass** [comment]
This needs more info and screenshots please. They don't render how?

**Comment by Penguin-Guru** [comment]
> This needs more info and screenshots please. They don't render how?

The tablet appears with the normal border and X button, but inside the border is pure grey. I've seen this before when there is a syntax error in Q.M.L., the whole app fails and just displays grey. I don't know if that's what's causing it in this case though.

I will try to figure out how to take a screenshot.

**Comment by Penguin-Guru** [comment]
![AppRun_h15m23s37](https://user-images.githubusercontent.com/22182988/169670862-702172b5-fb11-4439-a813-eabf6a741e35.png)

**Comment by ksuprynowicz** [comment]
We should look for what non rendering apps have in common. Maybe they use particular style sheet, or maybe all are HTML instead of QML? I wasn't able to find anything suspicious in the log.
Can you get logs from both source built version (where they render orrectly) and from AppImage? For each logged session open non rendering apps in the same order. Also try clearing cache.

**Comment by Penguin-Guru** [comment]
I cleared the cache using the AppImage because re-running the AppImage. The apps work in the compiled version without needing the cache to be cleared. I pruned the logs for regex "[Cc]hat" and then saved both of those results to upload here because there is a clear difference. I am also uploading the complete versions. When I ran the application each time, I waited for the domain to load, opened the Chat app from the toolbar, and then quit the application after confirming the results.

[does-not-work.log](https://github.com/overte-org/overte/files/8748521/does-not-work.log)
[does-not-work_pruned.log](https://github.com/overte-org/overte/files/8748522/does-not-work_pruned.log)
[works.log](https://github.com/overte-org/overte/files/8748523/works.log)
[works_pruned.log](https://github.com/overte-org/overte/files/8748524/works_pruned.log)

**Comment by ksuprynowicz** [comment]
Same problem happens with AppImage on Fedora 36. It also works correctly with source-built version.

**Comment by ksuprynowicz** [comment]
I noticed that Debian uses qtwebengine 5.15.8, even though rest of Qt is 5.15.2. I think that too old qtwebengine in the AppImage is causing problems.

**Comment by JulianGro** [comment]
Closing since we haven't heard of this happening in a long time.
Please reopen if the issue still occurs.
