### ISSUE TITLE
Rainbow Rectangle Appears Sporadically in Tutorial Domain.

### ISSUE THREAD

**Issue by Penguin-Guru** [overte-org/overte#64]
It fills about half of the window's width and height, always the same size and centred. It is a simple gradient fill-- the top left is green, top right is yellow, bottom right is red, and bottom left is black (I think). Tablet apps layer on top of the rectangle.

It disappears and reappears as I look around and move my avatar (either one). I **think** it appears when my avatar is looking toward the top part (not legs) of the Quick Setup console, even when my view of if it is obstructed.

Did not occur the one time I started the AppImage with my avatar in another domain and then clicked the Tutorial button in the top menu bar, but then it did appear after I clicked the button to clear all caches. Changing the graphics setting profile does not seem to change the behaviour.

Linux version 5.15.26
nvidia-firmware-340.32-r1
nvidia-drivers-470.103.01

**Comment by ksuprynowicz** [comment]
Confirmed on Debian Testing with Nvidia drivers. The problem happens only with AppImage and doesn't occur when building from source. To replicate go to tutorial and reload all content.

**Comment by JulianGro** [comment]
Appears with 74 on RTX 2060
Appears with Penguin-Guru on GTX 660
The issue does not appear on my system with a GTX 1080. I am also on Debian Testing and have the exact same driver. I am on Cinnamon.

**Comment by Penguin-Guru** [comment]
i3

**Comment by ksuprynowicz** [comment]
I tried debugging it with RenderDoc but it crashes when used on AppImage. When debugged with luci.js, disabling transparencies makes the rectangle disappear. Create App also crashes in tutorial really badly in AppImage, but doesn't crash in source-built version. Maybe when building from source newer Qt version is used?

**Comment by Penguin-Guru** [comment]
For reference, all of my system Qt packages are 5.15.3.

**Comment by ksuprynowicz** [comment]
It seems to be solved by this PR:
https://github.com/overte-org/overte/pull/125
For me the issue doesn't occur with the AppImage linked from that PR:
https://data.moto9000.moe/overte_appimages/Overte-x86_64-qt_update_2022.07.17.AppImage
Reopen the PR if it still occurs.

**Comment by Penguin-Guru** [comment]
I just tested that AppImage. It does seem to have solved the problem. I tried both connecting to the tutorial domain and clearing the cache then also disconnecting and reconnecting directly to the tutorial. There were no problems and the Quick Setup console seemed to work fine. 🙂
