### ISSUE TITLE
Oculus plugin is causing trouble on several different headsets

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#646]
Users with Virtual Desktop on Quest 2 and Pico headsets report it being impossible to use VR due to it. Pico Streaming Assistant is also broken with it. When using [experiment/disable_oculus](https://github.com/overte-org/overte/tree/experiment/disable_oculus) branch it all works well.
What would be the best way to optionally disable Oculus plugin in an user-friendly way without removing it?
I think we could disable it by default and provide some easy to use option to turn it on.

**Comment by MarcusLlewellyn** [comment]
Have they tried disabling Oculus support via the command line? OpenVR should still work when one does this, or at least it does for me with a quick test on Windows. For example:
`interface --disable-displays="Oculus Rift" --disable-inputs="Oculus Rift"`

**Comment by ksuprynowicz** [comment]
Yes. It did not help sadly.

**Comment by ksuprynowicz** [comment]
Fixed!
