### ISSUE TITLE
editing an entity's name updates the renderer

### ISSUE THREAD

**Issue by shocktail39** [overte-org/overte#651]
Entities.editProperties(uuid, {name:"something"}); will cause the renderer to update its transform and rerender, even if it hasn't moved at all.

**Comment by HifiExperiments** [comment]
I think this was a false alarm.  In https://github.com/overte-org/overte/issues/650, calling Entities.setLocalJointRotation sets _needsJointSimulation, so then any subsequent edit will trigger a render update.

In a simpler example, if I create an entity and just edit its name, it doesn't seem to trigger a render update.
