### ISSUE TITLE
First run starts in VR mode with no HMD connected

### ISSUE THREAD

**Issue by SilverfishVR** [overte-org/overte#680]
When starting Overte for the first time, or after restoring settings to default, it starts in VR mode if Steam VR is installed, even if no HMD is connected to the PC, since it captures the mouse cursor you have to tab out of Overte to navigate to the `Display` setting that only has one option; Desktop.

If no HMD is detected it should default to desktop mode, current behavior is a bad first impression.

Another curious thing is that in this mode, VR but no HMD connected, it uses 100% of the GPU.
![Screenshot 2023-10-27 21 37 31](https://github.com/overte-org/overte/assets/53531160/37e60d22-dbf1-4395-8309-d78245c35a7c)

**Comment by Colorfingers** [comment]
Steam just came out with a new upgrade... have you tried that?

**Comment by SilverfishVR** [comment]
I updated SteamVR to 2.0.8 same difference. 

Actually, when I wrote "if Steam VR is installed" that was an assumption, I don't actually know if that makes a difference, it does not start SteamVR, it starts in HMD simulator mode as far as I can tell from the _interface.json_
```
    "Display/Desktop": false,
    "Display/Disable Preview": true,
    "Display/HMD Simulator": true,
    "Display/Mono Preview": true,
```
and:
` "activeDisplayPlugin": "HMD Simulator",`

Here is my freshly generated _interface.json_ before any edits made by closing interface:
http://silverfish-freestuff.s3.amazonaws.com/TestStuff/Interface.json

**Comment by ksuprynowicz** [comment]
Thanks for investigating this!
It's surprising that the debug HMD plugin is enabled, since according to the source code it requires an environment variable:
```C++
const QString DebugHmdDisplayPlugin::NAME("HMD Simulator");

static const QString DEBUG_FLAG("HIFI_DEBUG_HMD");
static bool enableDebugHmd = QProcessEnvironment::systemEnvironment().contains(DEBUG_FLAG);


bool DebugHmdDisplayPlugin::isSupported() const {
    return enableDebugHmd;
}

void DebugHmdDisplayPlugin::resetSensors() {
    _currentRenderFrameInfo.renderPose = glm::mat4(); // identity
}
```

**Comment by ksuprynowicz** [comment]
Julian has just tested it on Windows and cannot reproduce the issue - when headset is disconnected and interface.json is deleted it starts in desktop mode. Maybe you have HIFI_DEBUG_HMD variable set?

**Comment by SilverfishVR** [comment]
Oh I did have that, I am very sorry for the confusion.
I did not realize that there was an environment variable for that to persist across installs,  I don't know when that was set but proberbly way back in the HIFI days. Yes, my windows install is that old, longest run I ever had 😄 
![Screenshot 2023-11-02 22 04 00](https://github.com/overte-org/overte/assets/53531160/25ed2e43-a16b-42eb-81f4-15b5165efff1)
Q: is this env still being set by Overte? and if so, Is there a design reason behind it or is it just legacy?

**Comment by JulianGro** [comment]
I don't think the environment variable would ever be set by anything other than you. So, no we don't set than variable. We only check if it is there and if it is set to true.
But yeah, so this isn't a bug then, it behaves exactly as it should.
