### ISSUE TITLE
Graphics setting switches to Low on its own

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#695]
When restarting Overte graphics setting switches to Low on its own. This happens especially after crash, even though user chooses to continue with current settings.

**Comment by daleglass** [comment]
Linux, but may also happen on Windows

**Comment by daleglass** [comment]
I recall that there's hardware autodetection on startup to set the default

**Comment by ksuprynowicz** [comment]
This looks very suspicious:
```C++
    static const QString firstRun;
```
It's an uninitalized constant string in libraries/shared/src/SettingHandle.h

I will have a PR ready soon

**Comment by ksuprynowicz** [comment]
It turns out it was initialized, IDE just wasn't showing it.

**Comment by ksuprynowicz** [comment]
It turns out this happens every time after a crash, even when I don't choose to reset settings.
To reproduce, set graphics settings to custom, and then cause a crash through developer menu.
Here's the backtrace:
```
PerformanceManager::setupPerformancePresetSettings(bool) PerformanceManager.cpp:38
Application::loadSettings(const QCommandLineParser &) Application.cpp:5532
Application::Application(int &, char **, const QCommandLineParser &, QElapsedTimer &, bool) Application.cpp:1943
main(int, const char **) main.cpp:599
WinMain(HINSTANCE__ *, HINSTANCE__ *, char *, int) qtmain_win.cpp:97
[Inlined] invoke_main() 0x00007ff6a30e28a2
__scrt_common_main_seh() 0x00007ff6a30e2881
<unknown> 0x00007ff993d27344
<unknown> 0x00007ff995c226b1
```

**Comment by ksuprynowicz** [comment]
It looks like this is fixed now :)
