### ISSUE TITLE
We need automated tests

### ISSUE THREAD

**Issue by daleglass** [overte-org/overte#74]
The code is well made for automated testing, and some should already exists, we're just not using them.

**Comment by Penguin-Guru** [comment]
Just for the record, my limited experience is that automated tests often end up broken for long periods of time and, even when they work properly, the output just confuses me when I try to contribute to a project. Also, GitHub sends a lot of emails about failures even if the failures were expected. Tests seem great in theory but that has been my experience so far.

**Comment by daleglass** [comment]
Fixed by PRs #78 and #79
