### ISSUE TITLE
Add tonemapping options to graphics settings

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#740]
Graphics settings should have a part or tab with advanced settings, and that section should feature different tonemapping algorithms, such as Filmic. We already have these algorithms available but they are accessible only from luci.js.

**Comment by SilverfishVR** [comment]
It should also include exposure setting: `Render.getConfig("RenderMainView.ToneMapping")["exposure"]`
and AO: `Render.setAmbientOcclusionEnabled()`

I think the Render API also provides ways to configure AO setting but I can't remember how.

**Comment by HifiExperiments** [comment]
now that time mapping is configurable through zones, I don’t think it makes sense to expose this in the graphics settings.  you can still override this using luci, but at least for now, I think we can close this
