### ISSUE TITLE
Create dropdowns are cut off by bottom of area

### ISSUE THREAD

**Issue by HifiExperiments** [overte-org/overte#750]
Dropdowns in Create near the bottom of the window will get cutoff.  This is evident in the "mirror mode" dropdown in https://github.com/overte-org/overte/pull/721 but is also visible on the shape type dropdown according to vegaslon

**Comment by SilverfishVR** [comment]
related: https://github.com/overte-org/overte/issues/188

**Comment by HifiExperiments** [comment]
ah, thank you!  closing as dupe
