### ISSUE TITLE
Add "copy UUID" to entity list context menu

### ISSUE THREAD

**Issue by SilverfishVR** [overte-org/overte#790]
To make it easier to get the ID of an entity
![Screenshot 2024-01-19 21 52 22](https://github.com/overte-org/overte/assets/53531160/f8121160-60de-442f-a271-886f03fdde60)

**Comment by SilverfishVR** [comment]
Maybe and/or add it to the Tools menu to be VR compatible.

**Comment by AleziaKurdis** [comment]
It would be more in the Edit menu (for VR) with the existing copy paste. (if there is room)

If we add this functionality, maybe we could also add it in the properties window next to the id property as a copy button.

**Comment by AleziaKurdis** [comment]
Is there a usecase where you would like to copy a selection of entitiesID ?

**Comment by Armored-Dragon** [comment]
Copy ID functionallity was merged in #865. Closing as completed.
