### ISSUE TITLE
Lighting flickering while wearing specific avatar

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte#799]
When wearing Annie from the Anime Avatars world, the lighting on some worlds appears to be flickering.
This does not happen with Woody. 

This *might* be a duplicate of https://github.com/overte-org/overte/issues/11, but I have almost exclusively seen that issue happen with blue, red, or green; I don't think I have ever seen it make everything darker.

This is on Window 11, with Intel UHD 630 graphics on driver version 31.0.101.2115.

**Comment by HifiExperiments** [comment]
closing this for now, we can re-open if it wasn't actually fixed by #845
