### ISSUE TITLE
Controls not properly mirrored in different views

### ISSUE THREAD

**Issue by Armored-Dragon** [overte-org/overte#821]
Issue:
When using the selfie mode, your controls are only partially mirrored. Only front/back controls are mirrored to match the perspective.

This is the same for the mouselook.js script. When using the mouselook.js script the controls for moving your screen are not properly mirrored.

**Comment by Armored-Dragon** [comment]
When your display is flipped, the "q" and "e" keys behave as you would expect the "a" and "d" keys.

**Comment by Armored-Dragon** [comment]
Related: #135

**Comment by HifiExperiments** [comment]
fyi this behavior is controlled by all the places that mention `Application.CameraSelfie` in this file: https://github.com/overte-org/overte/blob/master/interface/resources/controllers/keyboardMouse.json
