### ISSUE TITLE
Tablet needs attention message not showing up in VR

### ISSUE THREAD

**Issue by vegaslon** [overte-org/overte#822]
When click on for example the links on the edge of the table in the office at the hub in vr. The message that the table needs attention is not showing up to notify you that you need to answer the question, causes all your interactions after that point to pile up until you open the tablet to give your answer.

**Comment by AleziaKurdis** [comment]
The message is managed based on the signal Tablet tabletNotification signal.

I the documentation we have this note:

**Note: Only triggered if the script is running in the same script engine as the script that created the tablet. By default, this means in scripts included as part of the default scripts.**

Did we changed something recently that would make notifications.js unable to get this signal ?


Other possibility, if the controllers are over you headset, this clears the notifications. If the system get wrong data, it might trigger it immediately.

**Comment by vegaslon** [comment]
doing some digging it looks like it would be called here https://github.com/overte-org/overte/blob/68fffe00abe83343b22c3846b03800fd549959d7/libraries/ui/src/OffscreenUi.cpp#L298

**Comment by vegaslon** [comment]
Closing this since I was expecting to see the more reliable red notification that stuck around on the bottom of the VR view like the muted reminder and content loading but it would seem it has been switched out for a notification box that that does not like 360 tracking and likes to pop up behind head most of time.

**Comment by ksuprynowicz** [comment]
If it shows behind you it means that the whole 2D overlay is behind you too. It recenters every time you use movememt thumbstick.

**Comment by vegaslon** [comment]
notifications are not on the 2d overlay anymore they are made from local entities and for some reason they are not rotating with you when you move without joystick, and moving with joystick is not recentering them in view.

**Comment by AleziaKurdis** [comment]
Maybe we can redesing the displays and use the hud?
It was a disaster before I recoded notifications.js completely. It get a bit more stable  , but it's still unpredictible on the positionning.

**Comment by ksuprynowicz** [comment]
Can we move this discussion to a new issue instead of discussing it in a closed one?
Also I think that reworked notifications based on local entities are very good, there's no need to move them to the hud.
I'd suggest just improving the positioning instead if they show up behinf player sometimes.
