### ISSUE TITLE
Changing volume in People app does not work if person is not speaking

### ISSUE THREAD

**Issue by GooseVali** [overte-org/overte#839]
If you change someone's volume in the People app and the person is not speaking at the same time, the volume does not change even while the UI shows the desired new volume.

For it to work correctly, you have to time your clicks to happen while the person is talking.

Happens in both desktop and VR modes.

**Comment by ksuprynowicz** [comment]
It looks like problem is server side, packet gets to the server every time and AudioMixerClientData::setGainForAvatar correctly in AudioMixerClientData::parsePerAvatarGainSet, so the problem has to be somewhere aftert this.

**Comment by ksuprynowicz** [comment]
I built a version with added debug print and AudioHRTF::setGainAdjustment() is called only when someone is speaking
