### ISSUE TITLE
Cast shadow property for local lights

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#843]
We still won't have local light shadows for some time but soon we plan to change the protocol, so maybe add this change too?

**Comment by HifiExperiments** [comment]
I'd vote to wait until we actually implement the feature.  I don't love having unused properties cluttering things up, plus the create side would have to wait until later anyways.

the exact API might be more complicated than just a single bool, also.  e.g. we might want "shadow groups" where certain lights only cast shadows for certain objects or something like that, or the shadow properties might need to be configurable (like shadow bias is currently on the keylight)

**Comment by ksuprynowicz** [comment]
I agree. We should wait until it's actually implemented.
