### ISSUE TITLE
Keylight direction broken in latest master

### ISSUE THREAD

**Issue by SilverfishVR** [overte-org/overte#859]
The settings for keylight Vertical and horizontal angle in the create menu no longer work. It seems that the already set values still apply but changing them in create menu does nothing.
Setting it by script seems to work but it looks like getting the property returns an empty object:

```
> JSON.stringify(Entities.getEntityProperties("{b1dacebf-4811-42e3-9446-0a91fd68c0ad}", "keyLight.direction"));
< {}
```
getting a specific axis is the same:
```
> JSON.stringify(Entities.getEntityProperties("{b1dacebf-4811-42e3-9446-0a91fd68c0ad}", "keyLight.direction.x"));
< {}
```

If I do the same on current release I get all of the entity properties instead of just the direction so maybe this broke with the enterty properties PR #768 ? It is also broken on all the PR builds I have installed

Tested on win10 with master build 314.

**Comment by HifiExperiments** [comment]
I don't think `Entities.getEntityProperties(..., "keyLight.direction.x")` ever worked, in the same way that `Entities.getEntityProperties("..., "position.x")` never did.  maybe a feature request for another time.  but the linked PR should address getting the properties as both "keyLight" and "keyLight.direction"
