### ISSUE TITLE
Ability to release a domain name prematurely by hand

### ISSUE THREAD

**Issue by rampa3** [overte-org/overte#872]
I think it could be useful to allow user to voluntarily unregister (release) a domain name from the metaverse dashboard.

**Comment by JulianGro** [comment]
It works on my end: 
![Bildschirmfoto vom 2024-03-16 12-01-28](https://github.com/overte-org/overte/assets/11144627/cdd0163e-5a93-4de2-9050-ab0731f232f1)
Did you just not find the option?

**Comment by JulianGro** [comment]
Please reopen if this issue is still relevant.
