### ISSUE TITLE
Low AppImage performance

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#874]
It looks like AppImage performance is very poor again. On local RelWithDebInfo build I'm getting 7 times the performance of AppImage, which means that most possibly AppImage is built with -O0 again?

**Comment by JulianGro** [comment]
I cannot reproduce this on latest master.
(Left is newest release; right is master)
![Auswahl_162](https://github.com/overte-org/overte/assets/11144627/2077d397-dfed-4fc5-b520-82eb4cfd098b)

Here is the AppImage I created a couple of hours ago: https://data.moto9000.moe/Overte-2023.11.1-173-g3d5afbdd31-nodebug-x86_64.AppImage
(The filename presumably comes from the AppStream data. This is freshly cloned master.)

**Comment by ksuprynowicz** [comment]
For me in Overte Hub on master build engine time is about 10 ms and on Appimage I built it goes up to 130 ms, and sometimes 250 ms, resulting in framerates as low as 3 FPS.

**Comment by JulianGro** [comment]
I cannot actually join Overte Hub with a master AppImage, so I didn't test the Hub. It crashes on joining.

**Comment by ksuprynowicz** [comment]
Thanks! I'll investigate this today

**Comment by JulianGro** [comment]
> Thanks! I'll investigate this today

You can download the debug version as well: https://data.moto9000.moe/Overte-2023.11.1-173-g3d5afbdd31-debug-x86_64.AppImage
It looks like a deadlock, or rather humongous slowdown, related to `MultiSphereShape::computeSpheres`, though I thought that this was already fixed.

**Comment by ksuprynowicz** [comment]
It seems that the performance drop is caused by an unrelated bug in OpenGL drivers. The appimage itself is fine, and restrting system fixes this temporarily. I'll close this issue and open a new one if I'm able to find the cause of performance drop.

> You can download the debug version as well: https://data.moto9000.moe/Overte-2023.11.1-173-g3d5afbdd31-debug-x86_64.AppImage
> It looks like a deadlock, or rather humongous slowdown, related to MultiSphereShape::computeSpheres, though I thought that this was already fixed.

I tested it on newest master appimage and can't replicate the issue. Maybe it's avatar-related?

**Comment by JulianGro** [comment]
> I tested it on newest master appimage and can't replicate the issue. Maybe it's avatar-related?

I forgot about that. We meant to debug this last time, but I ended up being busy with other stuff.
