### ISSUE TITLE
Chat breaks URLs

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#922]
An example here:
![image](https://github.com/overte-org/overte/assets/11568651/9cc9ff28-d29d-45f9-a3e2-07b604691eec)
Actual link:
https://www.amazon.co.uk/gp/product/B0BGC9VRJ9/ref=ewc_pr_img_1?smid=A3P5ROKL5A1OLE&th=1

**Comment by daleglass** [comment]
Handled correctly in ArmoredChat
