### ISSUE TITLE
 MyAvatar.skeletonModelURL from Interface script is returning null even if it is from a local file

### ISSUE THREAD

**Issue by AleziaKurdis** [overte-org/overte#951]
MyAvatar.skeletonModelURL from Interface script is returning null even if it is from a  local file
 
 
![image](https://github.com/overte-org/overte/assets/60075796/636a3819-b6cd-4f96-b544-a31eff01e671)

 
 Download the community app repo on your machine
 run the application "flyAvatar"
 set a different avatar as your avatar for flight, and activate it.
 Fly and then do "Reload Content" (...or crash the system)
 Once back, then land somewhere. 
 Since the system recorded in the setting your avatar as you started fly...
the app try to keep the url of the non flyavatar. to deal with that later at the next startup. 
But it get null and fallback to woody.

**Comment by daleglass** [comment]
Being worked on in #955

**Comment by HifiExperiments** [comment]
I think this was resolved by the aforementioned PR
