### ISSUE TITLE
RC2 server log prints extra debug info

### ISSUE THREAD

**Issue by SilverfishVR** [overte-org/overte#992]
Any print() or console.log() prints out a whole block of info instead of just the message:
![Screenshot 2024-06-01 21 25 41](https://github.com/overte-org/overte/assets/53531160/856d1fe5-f4bc-4bd8-b650-967cd131cd6e)

That is not so bad but I have a script that instead of a few line of numbers, now prints several thousand of lines, not useable at all.

**Comment by SilverfishVR** [comment]
Also present in 2024.06.1 release.

**Comment by JulianGro** [comment]
What server package is that? The Windows installer?
